# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuburnHacks 2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuburnHacks 2019
  pod 'Firebase/Core'

  target 'AuburnHacks 2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuburnHacks 2019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
